### PR TITLE
add support for using more than 3 wav file to train a model

### PR DESCRIPTION
**Pull request by hanzala123**

### CODE REVIEW

**Comment by chenguoguo** [comment]
Thanks @hanzala123 for bringing this up. Unfortunately for the personal models, it will not work well when we have a lot of audio files, well in theory. Did you test on your end, and see if it helps when you have more audio examples (both accuracy and false alarm).

**Comment by hanzala123** [comment]
i tested it on my end using 12 wav files and it worked without any problems 
False alarms were reduced mostly because i used a quieter environment for the wav files.
I do think the accuracy has improved but i cannot tell for sure until i use it for a few days this is the model
https://github.com/hanzala123/models

**Comment by chenguoguo** [comment]
Thanks a lot for the info. I think it doesn't hurt to have that functionality, but I think we should design it properly for backward compatibility.

How about we make some changes:
1. We have an argument for --recording-dir, which is optional
2. If user provide --recording-dir, we load the recording_set from that directory, and we ignore --record1, record2 and record3. If user does provide --record1, --record2 or --record3, then we give warnings that they are overwritten by --recording-dir
3. If user does not provide --recording-dir, then we reply on --record1, --record2 and --record3, and if the user does not provide those, we let it fail.

What do you think?

**Comment by hanzala123** [comment]
That is indeed a good idea

**Comment by hanzala123** [comment]
@chenguoguo  i have made the necessary changes to generate_pmdl.py in my forked version. 
https://github.com/hanzala123/snowboy/blob/master/examples/Python/generate_pmdl.py

**Comment by hanzala123** [comment]
and pardon me for the patch-1 thing. this is my first time doing these things on github. So made a few mistakes.

**Comment by sveinbjornt** [comment]
What's the status on this?

**Pull request closed without merging**
